version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: directus_postgres
    restart: always
    environment:
      POSTGRES_DB: directus
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
    volumes:
      - postgres_data:/var/lib/postgresql/data

  directus:
    image: directus/directus:latest
    container_name: directus_cms
    restart: always
    depends_on:
      - postgres
    environment:
      KEY: "mysecretkey"
      SECRET: "myverysecretjwtkey"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "adminpassword"
      DB_CLIENT: "pg"
      DB_HOST: "postgres"
      DB_PORT: 5432
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"
      PUBLIC_URL: "http://localhost:8055"
    ports:
      - "8055:8055"
    volumes:
      - directus_data:/directus/database

volumes:
  postgres_data:
  directus_data:
